### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by jenokizm** [MatthewKing/DotNetVersionFinder#1]
![Ashampoo_Snap_2019 04 17_19h20m23s_008_](https://user-images.githubusercontent.com/11296510/56304076-fbffe500-6145-11e9-9a39-ee821dbc2245.png)

I have net 4.5.1

> Console.WriteLine(DotNetVersion.FindReleaseKey());
print number **379799** but 
Console.WriteLine(DotNetVersion.Find());
isnull, not detect full version number!

**Comment by MatthewKing** [comment]
That's odd.
Release key 379799 is not documented in the [official documentation](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies).
I've released a new version (1.1.1) that should handle undocumented release keys like this one.

Thanks.

**Comment by jenokizm** [comment]
thank. it's a good idea, only you hurried. correct 

> if (releaseKey > version.Key)

to

> if (releaseKey >= version.Key)

now its work for me!

**Comment by MatthewKing** [comment]
Thanks, good catch. I was hurrying to get to work! I've fixed it now, released as v1.1.2.

**Comment by jenokizm** [comment]
Thank you) I already got you and you will laugh, but you need to update your library again because today there are versions for 4.8 on those links from where you drew the information! =)

**Comment by jenokizm** [comment]
In addition, if you compare the information from the page where the minimum numbers and on the page where all the numbers, it becomes clear that there is an error. There is more than the minimum number for 4.8, that is 528040

**Comment by MatthewKing** [comment]
Oh wow, they updated the documentation just after I made my changes!

I see what you mean about the minimum version, too. [This document](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed) lists 528040 and 528049 as the release keys, but [this one](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/minimum-release-dword) incorrectly claims that 528049 is the minimum, when it is actually 528040.

Good catch! Thanks so much for your feedback and assistance.
